/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradersIndexRouteImport } from './routes/traders/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'
import { Route as TradersAddressRouteImport } from './routes/traders/$address'
import { Route as StrategiesNewRouteImport } from './routes/strategies/new'
import { Route as StrategiesIdRouteImport } from './routes/strategies/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersIndexRoute = TradersIndexRouteImport.update({
  id: '/traders/',
  path: '/traders/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradersAddressRoute = TradersAddressRouteImport.update({
  id: '/traders/$address',
  path: '/traders/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesNewRoute = StrategiesNewRouteImport.update({
  id: '/strategies/new',
  path: '/strategies/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIdRoute = StrategiesIdRouteImport.update({
  id: '/strategies/$id',
  path: '/strategies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/traders/$address': typeof TradersAddressRoute
  '/strategies': typeof StrategiesIndexRoute
  '/traders': typeof TradersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/traders/$address': typeof TradersAddressRoute
  '/strategies': typeof StrategiesIndexRoute
  '/traders': typeof TradersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/strategies/$id': typeof StrategiesIdRoute
  '/strategies/new': typeof StrategiesNewRoute
  '/traders/$address': typeof TradersAddressRoute
  '/strategies/': typeof StrategiesIndexRoute
  '/traders/': typeof TradersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/strategies/$id'
    | '/strategies/new'
    | '/traders/$address'
    | '/strategies'
    | '/traders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/strategies/$id'
    | '/strategies/new'
    | '/traders/$address'
    | '/strategies'
    | '/traders'
  id:
    | '__root__'
    | '/'
    | '/strategies/$id'
    | '/strategies/new'
    | '/traders/$address'
    | '/strategies/'
    | '/traders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StrategiesIdRoute: typeof StrategiesIdRoute
  StrategiesNewRoute: typeof StrategiesNewRoute
  TradersAddressRoute: typeof TradersAddressRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
  TradersIndexRoute: typeof TradersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders/': {
      id: '/traders/'
      path: '/traders'
      fullPath: '/traders'
      preLoaderRoute: typeof TradersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traders/$address': {
      id: '/traders/$address'
      path: '/traders/$address'
      fullPath: '/traders/$address'
      preLoaderRoute: typeof TradersAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/new': {
      id: '/strategies/new'
      path: '/strategies/new'
      fullPath: '/strategies/new'
      preLoaderRoute: typeof StrategiesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/$id': {
      id: '/strategies/$id'
      path: '/strategies/$id'
      fullPath: '/strategies/$id'
      preLoaderRoute: typeof StrategiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StrategiesIdRoute: StrategiesIdRoute,
  StrategiesNewRoute: StrategiesNewRoute,
  TradersAddressRoute: TradersAddressRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
  TradersIndexRoute: TradersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
